ARG ALPINE_VERSION=latest

FROM alpine:${ALPINE_VERSION}

RUN \
  apk --no-cache add ansible bash ca-certificates curl make openssl openssh-client tzdata && \
  ln -snf /etc/localtime /usr/share/zoneinfo/$TZ && echo $TZ > /etc/timezone && \
  rm -rf /var/cache/apk/*

RUN echo "alias l='ls --color -lha --group-directories-first'" > ~/.profile && \
    mkdir /app && \
    chmod 755 /app


WORKDIR /app

CMD ["bash", "-l"]