- name: check if snap command exists
  command: 'which snap'
  args:
    warn: no
  register: snap_exists
  ignore_errors: true

- name: Remove snaps
  snap:
    state: absent
    name: "{{ item }}"
  with_items:
    - lxd
    - core18
    - snapd
  ignore_errors: true
  when: snap_exists.rc == 1

- name: Remove snap package
  apt:
    name: snapd
    state: absent
    purge: yes
  when: snap_exists.rc == 1

- name: Clean artifact path
  file:
    state: absent
    path: "/etc/apt/apt.conf.d/20snapd.conf"