---
- include_tasks: create-cluster-node.yml
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node

- name: wait for all nodes to report ready
  shell: "kubectl get nodes -o wide | grep -v NotReady | grep Ready | wc -l"
  register: ready_count_output
  retries: 10
  until: ready_count_output.stdout|int == nodes|length
