---
- name: "Create kubeconfigs/traefik-chart-values.yml"
  template:
    src: "{{ playbook_dir }}/roles/{{ role_name }}/templates/metallb-config.yml.j2"
    dest: kubeconfigs/metallb-config.yml

- name: apply metallb config
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/namespace.yaml
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/metallb.yaml
    kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
    kubectl apply -f kubeconfigs/metallb-config.yml