additionalArguments:
  - --certificatesresolvers.letsencrypt.acme.email=mglenn@ilude.com
  - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
  - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  - --certificatesResolvers.letsencrypt.acme.dnschallenge=true
  - --certificatesResolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
  - --api.insecure=true
  - --accesslog=true
  - --log.level=INFO
env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: dns-token