---
###################################################
- name: prepare proxmox
  hosts: proxmox
  become: true
  gather_facts: no
  pre_tasks: 
    - import_tasks: common.yml
  roles:
    - prepare-proxmox

###################################################
- name: create template node
  import_playbook: create-template.yml
   
###################################################
- name: clone nodes from template image
  hosts: proxmox
  become: yes
  gather_facts: no
  pre_tasks:
    - import_tasks: common.yml
  roles:
    - clone-nodes

###################################################
- name: create cluster
  hosts: localhost
  become: no
  gather_facts: no
  pre_tasks:
    - import_tasks: common.yml
  roles:
    - create-cluster

- name: snapshot nodes
  hosts: proxmox
  become: yes
  gather_facts: no
  pre_tasks:
    - import_tasks: common.yml
  tasks:
    - include_tasks: common-snapshot-node.yml
      loop: "{{ nodes }}"
      loop_control:
        loop_var: node

- import_playbook: create-loadbalancer.yml
